/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ai/parse-task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Task */
        post: operations["parse_task_api_v1_ai_parse_task_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Archive */
        get: operations["list_archive_api_v1_archive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archive/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Archived Task */
        get: operations["get_archived_task_api_v1_archive__task_id__get"];
        put?: never;
        post?: never;
        /** Delete Archived Task */
        delete: operations["delete_archived_task_api_v1_archive__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archive/{task_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Task */
        post: operations["restore_task_api_v1_archive__task_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Session */
        get: operations["read_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/actions/{action_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Action
         * @description Apply a pending proposal's write (spec §41). Calls no LLM. Every
         *     documented failure (`404`, `409 ACTION_ALREADY_REJECTED`,
         *     `409 ACTION_STALE`) is raised by `db.chat_action_repository.confirm`
         *     itself and propagates unchanged through this route.
         */
        post: operations["confirm_action_api_v1_chat_actions__action_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/actions/{action_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Action
         * @description Reject a pending proposal (spec §41). Calls no LLM. The only
         *     documented failure (`409 ACTION_ALREADY_APPLIED`) is raised by
         *     `db.chat_action_repository.reject` itself.
         */
        post: operations["reject_action_api_v1_chat_actions__action_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/conversation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Conversation */
        get: operations["read_conversation_api_v1_chat_conversation_get"];
        put?: never;
        /** Reset Conversation */
        post: operations["reset_conversation_api_v1_chat_conversation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Send one user message and return the full, updated conversation.
         *
         *     No write happens before `send_chat_message` returns successfully — a
         *     failure anywhere in its tool-call loop (an `LLMUnavailableError`,
         *     surfaced as `503 AI_UNAVAILABLE` by `ai.client.register_llm_error_
         *     handler`) propagates straight out of this route, and `api.deps.get_db`
         *     rolls back the request's transaction, so neither the user turn, an
         *     assistant turn, nor any proposal is ever persisted (spec §10.4).
         *
         *     Issue #41: the first proposal the turn produced (if any) is attached to
         *     the one assistant message that carries the model's final text; each
         *     further proposal gets its own assistant message with empty text, in
         *     call order — never a `task` row, which only a later confirm writes.
         */
        post: operations["send_message_api_v1_chat_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_v1_settings_patch"];
        trace?: never;
    };
    "/api/v1/settings/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_settings_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Tasks */
        post: operations["reorder_tasks_api_v1_tasks_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_api_v1_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Task
         * @description Board drag (or an AI-confirmed move), cross-column or within one
         *     column (issue #29). `completed_at` always goes through
         *     `resolve_completed_at` — entering, leaving and staying in Done are all
         *     handled by that one rule, never re-implemented here.
         */
        post: operations["move_task_api_v1_tasks__task_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArchiveListResponse
         * @description The full-page shape for `GET /api/v1/archive`.
         */
        ArchiveListResponse: {
            /** Items */
            items: components["schemas"]["TaskResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * ChatActionFieldResponse
         * @description One `{label, from, to}` preview entry (spec §41). `from` is a
         *     reserved Python keyword, so the attribute is `from_`, populated either
         *     by that name or by its wire alias `from` — FastAPI's default
         *     `response_model_by_alias=True` always serializes it as `from`.
         */
        ChatActionFieldResponse: {
            /** From */
            from?: string | null;
            /** Label */
            label: string;
            /** To */
            to: string;
        };
        /**
         * ChatActionKind
         * @enum {string}
         */
        ChatActionKind: "create" | "update" | "move" | "schedule";
        /**
         * ChatActionResponse
         * @description One proposed action, attached to the assistant message that carries
         *     it (spec §41). `payload` is a kind-specific dict — `{"draft": ...}` for
         *     `create`, `{"task_id": ..., "draft": ...}` for `update`, `{"task_id":
         *     ..., "status": ...}` for `move`, `{"task_id": ..., "deadline_at": ...}`
         *     for `schedule` — built once at proposal time by `ai.propose_tools` and
         *     stored verbatim; this schema does not re-derive it.
         */
        ChatActionResponse: {
            /** Fields */
            fields: components["schemas"]["ChatActionFieldResponse"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["ChatActionKind"];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            status: components["schemas"]["ChatActionStatus"];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /**
         * ChatActionStatus
         * @enum {string}
         */
        ChatActionStatus: "pending" | "applied" | "rejected";
        /**
         * ChatMessageResponse
         * @description One message on the wire — `id`, `role`, `text`, `created_at`, and
         *     `action` (spec §41: `null` on a user message, on an assistant message
         *     with no proposal, and on a confirmation message; otherwise the
         *     proposal it carries).
         */
        ChatMessageResponse: {
            action?: components["schemas"]["ChatActionResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["ChatRole"];
            /** Text */
            text: string;
        };
        /**
         * ChatRole
         * @enum {string}
         */
        ChatRole: "user" | "assistant";
        /**
         * ConversationResponse
         * @description The full conversation wire shape — exactly `id` and `messages`.
         */
        ConversationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Messages */
            messages: components["schemas"]["ChatMessageResponse"][];
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Details */
            details?: components["schemas"]["ValidationErrorDetail"][] | null;
            /** Message */
            message: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * ParseTaskRequest
         * @description `POST /api/v1/ai/parse-task` request body. `text` is required to be
         *     1 to 4000 characters *after* trimming; the trimmed value is what the
         *     router and the model both see — an over-length, empty, whitespace-only,
         *     missing or non-string `text` is rejected here, before the model is
         *     ever called.
         */
        ParseTaskRequest: {
            /** Text */
            text: string;
        };
        /**
         * ParsedTaskResponse
         * @description The `TaskDraft` wire shape (spec §6.2) — exactly what a confirmed
         *     preview later posts, unchanged, to `POST /api/v1/tasks`
         *     (`schemas.task.TaskCreate` minus `status`). No `id`, no `status`, and
         *     no server timestamp: this is a proposal, not a persisted task (spec
         *     §6.2: "The LLM may only propose values. It does not save a task
         *     directly").
         */
        ParsedTaskResponse: {
            category: components["schemas"]["TaskCategory"];
            /** Content */
            content: string;
            /** Deadline At */
            deadline_at?: string | null;
            /**
             * Markdown Note
             * @default
             */
            markdown_note: string;
            priority: components["schemas"]["TaskPriority"];
            /** Title */
            title: string;
            /** Urls */
            urls?: components["schemas"]["TaskUrl"][];
        };
        /**
         * PasswordChangeRequest
         * @description `POST /api/v1/settings/password` request body (spec §3.2).
         *
         *     Passwords are compared and hashed verbatim — never trimmed. Only
         *     `new_password`'s length is checked here (before any database or Argon2
         *     work); `current_password` is validated by the router, against the
         *     stored hash, so an invalid `new_password` never costs an Argon2
         *     verification. The length rule itself is `security.password`'s shared
         *     definition (issue #33 moved it there so #33's administrative reset
         *     command can reuse it without a second copy of the rule).
         */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * SendMessageRequest
         * @description `POST /api/v1/chat/messages` request body (issue #40). `text` is
         *     required to be 1 to 4000 characters *after* trimming — the same rule
         *     `schemas.ai.ParseTaskRequest` uses — and the trimmed value is what is
         *     persisted and sent to the model. An extra field, a missing field, a
         *     blank value, or an over-length value is rejected here, before the
         *     model is ever called and before any row is written.
         */
        SendMessageRequest: {
            /** Text */
            text: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Signed In At */
            signed_in_at: string;
            /** Username */
            username: string;
        };
        /**
         * SettingsResponse
         * @description The full settings wire shape — exactly `timezone`, `model_name` and
         *     `available_models`, nothing else; never a secret (spec §11).
         *     `available_models` is read-only: the models the deployment serves.
         */
        SettingsResponse: {
            /** Available Models */
            available_models: string[];
            /** Model Name */
            model_name: string;
            /** Timezone */
            timezone: string;
        };
        /**
         * SettingsUpdate
         * @description `PATCH /api/v1/settings` request body — a partial update.
         *
         *     Both fields default to `None`, meaning "left out of the body"; the
         *     router distinguishes that from an explicit value via
         *     `model_dump(exclude_unset=True)` (pydantic does not run a field
         *     validator against a default that was never supplied — only against a
         *     value actually present in the request). An explicit `null` for either
         *     field is therefore *not* a valid way to clear an override back to the
         *     deployment default — this schema rejects it outright, matching the
         *     acceptance criteria.
         *
         *     Extra fields (`llm_api_key`, `llm_base_url`, `database_url`,
         *     `session_secret`, `password`, ...) are rejected outright: secrets and
         *     database configuration are never editable through the browser
         *     (spec §11).
         */
        SettingsUpdate: {
            /** Model Name */
            model_name?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /**
         * TaskCategory
         * @enum {string}
         */
        TaskCategory: "work" | "personal" | "study" | "other";
        /**
         * TaskCreate
         * @description `POST /api/v1/tasks` request body (spec §6.1 defaults).
         *
         *     Extra fields are rejected outright — both truly unknown keys and every
         *     server-owned field (`id`, `position`, `created_at`, `updated_at`,
         *     `completed_at`, `archived_at`), none of which this model declares, so
         *     they can never be silently dropped or, worse, silently honored.
         */
        TaskCreate: {
            /** @default other */
            category: components["schemas"]["TaskCategory"];
            /** Content */
            content: string;
            /** Deadline At */
            deadline_at?: string | null;
            /**
             * Markdown Note
             * @default
             */
            markdown_note: string;
            /** @default medium */
            priority: components["schemas"]["TaskPriority"];
            /** @default todo */
            status: components["schemas"]["TaskStatus"];
            /** Title */
            title: string;
            /** Urls */
            urls?: components["schemas"]["TaskUrl"][];
        };
        /**
         * TaskMove
         * @description `POST /api/v1/tasks/{task_id}/move` request body (issue #29).
         *
         *     `index` is an insertion index, not a stored `position` value — for a
         *     move into another column it is the index among that column's existing
         *     tasks (`0` to `len(target)` inclusive); for a move whose `status`
         *     equals the task's current one it is the task's final index in its own
         *     column (`0` to `len(column) - 1` inclusive). Both bounds depend on the
         *     target column's size at request time, so only the lower bound (never
         *     negative) is enforced by the wire type here — the upper bound is
         *     checked by `domain/ordering.py` and turned into a `422` by the router;
         *     neither bound is ever clamped.
         */
        TaskMove: {
            /** Index */
            index: number;
            status: components["schemas"]["TaskStatus"];
        };
        /**
         * TaskPriority
         * @enum {string}
         */
        TaskPriority: "low" | "medium" | "high";
        /**
         * TaskReorder
         * @description `POST /api/v1/tasks/reorder` request body (issue #29).
         *
         *     `ordered_ids` must be an exact permutation of the ids of the active
         *     tasks currently in `status` — checked by `domain/ordering.reorder_column`
         *     and turned into a `422` by the router for a duplicate, an omission, or
         *     a foreign/archived/unknown id.
         */
        TaskReorder: {
            /** Ordered Ids */
            ordered_ids: string[];
            status: components["schemas"]["TaskStatus"];
        };
        /**
         * TaskResponse
         * @description The full task wire shape — exactly the 14 §5 fields, nothing else.
         */
        TaskResponse: {
            /** Archived At */
            archived_at: string | null;
            category: components["schemas"]["TaskCategory"];
            /** Completed At */
            completed_at: string | null;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deadline At */
            deadline_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Markdown Note */
            markdown_note: string;
            /** Position */
            position: number;
            priority: components["schemas"]["TaskPriority"];
            status: components["schemas"]["TaskStatus"];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Urls */
            urls: components["schemas"]["TaskUrl"][];
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "todo" | "in_progress" | "done";
        /**
         * TaskUpdate
         * @description `PATCH /api/v1/tasks/{id}` request body — a partial update.
         *
         *     Every field defaults to `None`, meaning "left out of the body" — the
         *     router distinguishes that from an *explicit* `null` via
         *     `model_dump(exclude_unset=True)`, since pydantic does not run a field's
         *     validators against a default value that was never supplied (only
         *     against a value actually present in the request, including an explicit
         *     `null`). An explicit `null` for a field the database stores `NOT NULL`
         *     (`title`, `content`, `markdown_note`, `category`, `priority`, `status`,
         *     `urls`) is rejected by the validators below; only `deadline_at` accepts
         *     an explicit `null`, which clears the deadline.
         */
        TaskUpdate: {
            category?: components["schemas"]["TaskCategory"] | null;
            /** Content */
            content?: string | null;
            /** Deadline At */
            deadline_at?: string | null;
            /** Markdown Note */
            markdown_note?: string | null;
            priority?: components["schemas"]["TaskPriority"] | null;
            status?: components["schemas"]["TaskStatus"] | null;
            /** Title */
            title?: string | null;
            /** Urls */
            urls?: components["schemas"]["TaskUrl"][] | null;
        };
        /**
         * TaskUrl
         * @description One URL entry (spec §5, §8). No `id` on the wire — the web tier's
         *     HTTP mapper assigns a client-side id for its own `TaskUrl.id` (the
         *     user's non-scope decision recorded on issue #28: URL entries stay
         *     id-less on the wire).
         */
        TaskUrl: {
            /** Label */
            label?: string | null;
            /** Url */
            url: string;
        };
        /** ValidationErrorDetail */
        ValidationErrorDetail: {
            /** Code */
            code: string;
            /** Field */
            field: string | null;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    parse_task_api_v1_ai_parse_task_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedTaskResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_archive_api_v1_archive_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on title only. Leading/trailing whitespace is trimmed; blank behaves as no search. */
                search?: string | null;
                /** @description 1-based page number. */
                page?: number;
                /** @description Items per page, up to 100. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveListResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_archived_task_api_v1_archive__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_archived_task_api_v1_archive__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restore_task_api_v1_archive__task_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"] | null;
                };
            };
        };
    };
    confirm_action_api_v1_chat_actions__action_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reject_action_api_v1_chat_actions__action_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_conversation_api_v1_chat_conversation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_conversation_api_v1_chat_conversation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    send_message_api_v1_chat_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_settings_api_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_password_api_v1_settings_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description API error envelope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reorder_tasks_api_v1_tasks_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskReorder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_task_api_v1_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    move_task_api_v1_tasks__task_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"][];
                };
            };
            /** @description API error envelope */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API error envelope */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request fields */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
