import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

// schema.gen.ts is generated by `bun run gen:api-types` (#34) from
// apps/api/openapi.json and must never be hand-edited (binding rule 4).
// This guards the "types only" contract: a generated client or any runtime
// export here would give components a second way to reach the API,
// dissolving the ApiClient seam (binding rule 3).
//
// Vitest runs from the apps/web root, so the path is resolved from there
// rather than import.meta.url (which jsdom does not expose as a file: URL).
const schemaPath = resolve(process.cwd(), "src/shared/api/schema.gen.ts");
const source = readFileSync(schemaPath, "utf-8");

describe("schema.gen.ts", () => {
  it("carries the generator's do-not-edit header", () => {
    expect(source).toMatch(/auto-generated by openapi-typescript/);
    expect(source).toMatch(/do not make direct changes/i);
  });

  it("declares no runtime exports", () => {
    // Only type-level declarations are allowed: `export interface`,
    // `export type`. No `export const`, `export function`, `export class`
    // or `export enum` — any of those would emit runtime code.
    expect(source).not.toMatch(/^export const /m);
    expect(source).not.toMatch(/^export function /m);
    expect(source).not.toMatch(/^export class /m);
    expect(source).not.toMatch(/^export enum /m);
    expect(source).not.toMatch(/^export default /m);
  });

  it("declares only types and interfaces", () => {
    const exportLines = source.split("\n").filter((line) => line.startsWith("export "));
    expect(exportLines.length).toBeGreaterThan(0);
    for (const line of exportLines) {
      expect(line).toMatch(/^export (interface|type)\b/);
    }
  });
});
